name: Build

on:
    push:
        branches:
            - main
    pull_request:

concurrency:
    group: build-${{ github.ref }}
    cancel-in-progress: true

jobs:
    test_and_apk:
        name: "Local tests and APKs"
        runs-on: ubuntu-latest

        permissions:
            contents: write

        timeout-minutes: 60

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Validate Gradle Wrapper
              uses: gradle/wrapper-validation-action@v2

            - name: Copy CI gradle.properties
              run: mkdir -p ~/.gradle ; cp .github/ci-gradle.properties ~/.gradle/gradle.properties

            - name: Set up JDK 17
              uses: actions/setup-java@v4
              with:
                  distribution: 'zulu'
                  java-version: 17

            - name: Setup Gradle
              uses: gradle/gradle-build-action@v3

            - name: Check build-logic
              run: ./gradlew check -p build-logic

            - name: Check spotless
              run: ./gradlew spotlessCheck --no-configuration-cache

            - name: Check Dependency Guard
              id: dependencyguard_verify
              continue-on-error: true
              run: ./gradlew dependencyGuard

            - name: Run all local screenshot tests (Roborazzi)
              id: screenshotsverify
              continue-on-error: true
              run: ./gradlew verifyRoborazziDebug

            # Runs if previous job failed
            - name: Generate new screenshots if verification failed and it's a PR
              id: screenshotsrecord
              if: steps.screenshotsverify.outcome == 'failure' && github.event_name == 'pull_request'
              run: |
                  ./gradlew recordRoborazziDemoDebug

            - name: Push new screenshots if available
              uses: stefanzweifel/git-auto-commit-action@v5
              if: steps.screenshotsrecord.outcome == 'success'
              with:
                  file_pattern: '*/*.png'
                  disable_globbing: true
                  commit_message: "🤖 Updates screenshots"

            - name: Run local tests
              if: always()
              run: ./gradlew testDebug
            # Replace task exclusions with `-Pandroidx.baselineprofile.skipgeneration` when
            # https://android-review.googlesource.com/c/platform/frameworks/support/+/2602790 landed in a
            # release build
            - name: Build all build type and flavor permutations
              run: ./gradlew :app:assemble

            - name: Upload build outputs (APKs)
              uses: actions/upload-artifact@v4
              with:
                  name: APKs
                  path: '**/build/outputs/apk/**/*.apk'

            - name: Upload test results (XML)
              if: always()
              uses: actions/upload-artifact@v4
              with:
                  name: test-results
                  path: '**/build/test-results/test*UnitTest/**.xml'

            - name: Check lint
              run: ./gradlew :app:lintRelease lint

            - name: Upload lint reports (HTML)
              if: always()
              uses: actions/upload-artifact@v4
              with:
                  name: lint-reports
                  path: '**/build/reports/lint-results-*.html'
